# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: ./main.go
    id: dbmill-cli
    binary: dbmill-cli
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ignore:
      - goos: linux
        goarch: 386
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -X 'github.com/vitpelekhaty/dbmill-cli/cmd/commands.Version={{.Version}}' -X 'github.com/vitpelekhaty/dbmill-cli/cmd/commands.GitCommit={{.ShortCommit}}' -X 'github.com/vitpelekhaty/dbmill-cli/cmd/commands.Built={{.Date}}'
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
